language: android
dist: trusty

before_install:
  - wget https://services.gradle.org/distributions/gradle-5.6.4-bin.zip
  - unzip gradle-5.6.4-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.6.4
  - export PATH=$GRADLE_HOME/bin:$PATH
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk -a --no-ui --filter tool,platform-tool,build-tools-28.0.3,build-tools-29.0.2,android-29
  - echo y | sdkmanager --update
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "ndk;21.0.6113669"
  - echo y | sdkmanager "cmake;3.10.2.4988404"

script:
  - gradle lint
  - gradle assembleDebug

android:
  components:
    - platform-tools
    - tools
    - build-tools-29
    - android-29

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
